[package]
name = "adaptivegrain-rs"
version = "0.3.2"
authors = ["kageru"]
edition = "2024"

[dependencies]
anyhow = "*"
vapoursynth = "*"
vapoursynth-sys = "*"

[lib]
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "mask"
harness = false
