name: Publish

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build-release-binaries:
    uses: ./.github/workflows/build-release-binaries.yml

  publish:
    needs: [build-release-binaries]
    name: publish
    runs-on: ubuntu-24.04

    environment:
      name: pypi
      url: https://pypi.org/p/vapoursynth-adaptivegrain

    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
